### ISSUE TITLE
Remove date calculations from social media notifications

### ISSUE THREAD

**Issue by vexx32** [chocolatey/Chocolatey.Cake.Recipe#168]
### Checklist

- [x] I have verified this is the correct repository for opening this issue.
- [x] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

Previously we needed to use a date to reference release notes sections, but this has been updated to use the version number for the anchor, so we can remove this code.

### Describe The Solution. Why is it needed?

Take out the date code here and simplify so we only need use the version in the .notifications template files.

**Comment by corbob** [comment]
Is this not the same as #164?

**Comment by vexx32** [comment]
It is, didn't catch that one, cheers, closing.
