### ISSUE TITLE
Add support for running PSScriptAnalyzer

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/Chocolatey.Cake.Recipe#32]
## Is Your Feature Request Related To A Problem? Please describe.

Chocolatey CLI has an open issue (chocolatey/choco#2703) to add a run of PSScriptAnalyzer as part of the build.

## Describe The Solution. Why is it needed?

As Chocolatey CLI is moving to using Chocolatey.Cake.Recipe, it would be appropriate to add code here so as to be able to run PSScriptAnalyzer as part of the build.

## Additional Context.

It probably would be appropriate to use a `PSScriptAnalyzerSettings.psd1` to set the options for PSScriptAnalyzer. I'm not sure if that means putting one in this repository, and having the option to override it, or requiring a `PSScriptAnalyzerSettings.psd1` file for each project. If it is the second, perhaps if the file exists, that could be a signal to run PSScriptAnalyzer?

Also, there may need to be extra code added to exclude specific folder(s) where pester tests live, as they may produce false positives. See: https://github.com/chocolatey/choco/pull/2596#issuecomment-1043427547

## Related Issues

- Issue chocolatey/choco#2400
- Issue chocolatey/choco#2703

**Comment by gep13** [comment]
> @TheCakeIsNaOH said...
If it is the second, perhaps if the file exists, that could be a signal to run PSScriptAnalyzer?

This seems like a sensible idea to me, yes.

And for this...

> @TheCakeIsNaOH said....
Also, there may need to be extra code added to exclude specific folder(s) where pester tests live, as they may produce false positives

This would be an addition to the `ToolSettings.SetToolSettings` method.

**Comment by TheCakeIsNaOH** [comment]
Long term, it probably would be ideal to reference PSScriptAnalyzer into Cake as a .Net library, instead of shelling out to run it: 
https://docs.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/using-scriptanalyzer?view=ps-modules#scriptanalyzer-as-a-net-library

Unfortunately, it is not published as a library to NuGet.org currently: https://github.com/PowerShell/PSScriptAnalyzer/issues/747

So, it seems like it might be possible to use the PSGallery `.nupkg` to get the required assemblies, and package that into a Cake module, which can then be used, but that is a decently sized project.

However, currently, it should be fine to instead shell out to PowerShell and use the module version. 

There is also a potentially interesting module that converts the output of PSScriptAnalyzer to an interchange format: https://www.powershellgallery.com/packages/ConvertToSARIF/1.0.0

**Comment by TheCakeIsNaOH** [comment]
Hmm, I didn't realize that `UseCompatibleCmdlets` has a PowerShell version 2 settings file available: 
https://docs.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/usecompatiblecmdlets?view=ps-modules

It would not be full checking by using all the `UseCompatible*` rules, but better than nothing.

**Comment by gep13** [comment]
> @TheCakeIsNaOH said...
Long term, it probably would be ideal to reference PSScriptAnalyzer into Cake as a .Net library, instead of shelling out to run it:

I tried to do this, but long story short, it was going to be more trouble than it was worth, so instead, I opted to create a new `RequirePSModule` method, which can be used to install required PS Modules, when required as part of the build.

> @TheCakeIsNaOH said...
There is also a potentially interesting module that converts the output of PSScriptAnalyzer to an interchange format:

I have added this to the PR, as I think there is some merit in having the output in this format.
