### ISSUE TITLE
When GitReleaseManager cannot be used, the message should explain what it was looking for

### ISSUE THREAD

**Issue by corbob** [chocolatey/Chocolatey.Cake.Recipe#78]
## Is Your Feature Request Related To A Problem? Please describe.

When GitReleaseManager is not able to be used, the message is `Unable to use GitReleaseManager, as necessary credentials are not available`. This is not helpful to the user running the script as it doesn't explain what credentials might be necessary.

## Describe The Solution. Why is it needed?

The warning would ideally list at least one of the potential environment variables that are checked for the necessary credentials.

## Additional Context.

I encountered this when trying to do a Chocolatey GUI release, and had to look into the Recipe itself to find the environment variables to use.

## Related Issues

N/A

**Comment by gep13** [comment]
@corbob happy for you to add a Pull Request to get this improved.
